### ISSUE TITLE
Calendar Hangs on load

### ISSUE THREAD

**Issue by BigActual** [Good-Shepherd-Catholic-Radio/Theme-2017#28]
No further description was given. Though during the meeting with Harry, we loaded the calendar and it started like a snail on Pot.

**Comment by BigActual** [comment]
Also, I have a note that the calendar shows the schedule and that was confusing. This is probably one of the most severe issues we talked about.

**Comment by BigActual** [comment]
Harry asked me to ensure that there was a definite difference between a schedule and an event.

**Comment by d4mation** [comment]
Calendar is not meant to show the Schedule. That's odd. 

I believe it only fails to load if the Calendar is loaded via AJAX. If you load the Calendar directly, it loads properly. This needs to be investigated.

**Comment by d4mation** [comment]
> I have a note that the calendar shows the schedule and that was confusing

Do you mean on this page? http://gscr.realbigwebsites.com/events/category/radio-show/

That page is special as I have specifically coded the site so that if the Radio Show Category is queried (It is normally hidden) that they will show on the Calendar.

If you look at the regular Events Calendar, the Radio Shows are not present:
http://gscr.realbigwebsites.com/events/

Given the existence of the Schedule page, I'm not sure why a link to the Radio Shows Category page exists in the Navigation. It should/could be removed.

![image](https://user-images.githubusercontent.com/7770631/27889219-ea51b1b4-61b8-11e7-8476-3b0e40600a7e.png)
