### ISSUE TITLE
Radio Show Current/Upcoming Schedule on Home Page needs rework

### ISSUE THREAD

**Issue by BigActual** [Good-Shepherd-Catholic-Radio/Theme-2017#33]
The client wants to make better use of the space here. The bar is horizontally quite tall and takes a lot of space. The client would like us to rework this area to be shorter and or thinner. To incorporate donation, listen, and learn equally, above the fold.

The client and I had a deep conversation about the effectiveness of "Above the Fold" in 2017. How people actually do scroll south. The client understands this.

However, I acknowledge that there is a better balance at the top of the page. We can do better. Let's discuss and move forward.

**Comment by d4mation** [comment]
To be clear, which is the "bar"?

I figure it is the Now Playing/Upcoming Radio Shows section, but I am not sure.

Adjusting the Height there should be quite simple. https://github.com/Good-Shepherd-Catholic-Radio/Theme-2017/blob/3d1617c4422e673444af0581fdc8ebd293087bf4/build/sass/templates/home/_radio-shows-header.scss#L1

![image](https://user-images.githubusercontent.com/7770631/27879615-3d614c08-6190-11e7-9d88-d0d30ea3b286.png)

**Comment by BigActual** [comment]
You are correct. the lower ? in your illustration above

**Comment by d4mation** [comment]
Shrunk from 500px tall for 350px tall. 

I wanted to ensure that the smaller rectangles on the right didn't become too squished as they are half the height of the primary container.

More will be visible "above the fold" with #14 and probably #15.

![image](https://user-images.githubusercontent.com/7770631/27957525-de87e508-62ec-11e7-8111-ba69436efa86.png)

**Comment by BigActual** [comment]
Thanks for your patience with this Eric. Here's what we discussed:
Move the tiles up and behind the title, Now Playing so that there is butted against the purple menu bar
Remove the show information and icons in the default state
On Hover, Remove Now Playing and show the show information. Fade Out fade in would be good I suppose, but pretty darn fast
Take the number of Upcoming Shows down to two, over under, not side by side
Add the title "Upcoming" a the same x axis placement as "Now Playing"
As was done in the Now Playing section, show the title in the default state and on hover show the program information and icons
Reduce the title sizes of all titles to be the same size as Support Good Shepherd and Listening Options
Adjust the horizontal sizing o the two right blocks, Support... and Listening... so they balance vertically with the shows to the right. Titles too.
Add background images to the Support GSCR and Listening Options boxes. Those are provided by me soon.

**Comment by d4mation** [comment]
> Reduce the title sizes of all titles to be the same size as Support Good Shepherd and Listening Options

Do you mean _every_ Header on the Home Page? Just the "Now Playing/Up Next" text?

**Comment by BigActual** [comment]
Every one of them

**Comment by BigActual** [comment]
I'm sorry to say that there's some additional work to do here as a result of the styling we elected to work with on the single pages. Those require a wide hero image on each one. That hero image then does not work well with the space allotted in the current configuration. We have to reassess how much width to give the shows on the home page and then, how to apply the text overlay. I've created quite a few of these images and have consistently provided room on the left to place the copy with the subject of the show to the right; the Personality, or the shows graphic, etc.

**Comment by d4mation** [comment]
For the Radio Show images in the header, I have all of those set to center horizontally and vertically within the container and then scale to fit at each edge. So if they're all set so the subject matter is on the right and text is on the left then I guess that will be a problem. 

That causes this:

![image](https://user-images.githubusercontent.com/7770631/28522914-ff80cdac-7047-11e7-9d47-b24e75c7458d.png)

To become this:

![image](https://user-images.githubusercontent.com/7770631/28522918-067dedce-7048-11e7-974d-3e6b75ec4390.png)

However, if I adjust the background positioning I can move things over significantly:

![image](https://user-images.githubusercontent.com/7770631/28522941-1efb6930-7048-11e7-9e7c-366875a97f84.png)

That does mess with the Placeholder images, but those hopefully won't be there for too much longer anyhow.

If all the Radio Show images are to be this way, this could just be a quick CSS tweak rather than having to use separate images :+1:

**Comment by d4mation** [comment]
With the removal of the Purple Background, for some Radio Shows it becomes slightly harder to read the Header text. This is mostly due to the shapes intersecting it from behind and the small width of the lines for the letters.

![image](https://user-images.githubusercontent.com/7770631/28580518-b5e97dec-712d-11e7-93aa-9dc64de281e1.png)

This could likely be avoided by maintaining a particular style like in the screenshot in my last comment though. With the background on the image for Teresa Tomeo's show this is not an issue. 

We could also bump up the stroke on the header to further differentiate it, but there are some odd rendering issues with this particular font that can be noticed if you zoom in on it which would be more pronounced with a larger stroke (Check "R" and "A"):

![image](https://user-images.githubusercontent.com/7770631/28580579-e27f33ec-712d-11e7-9288-99a85ae1c3ac.png)

This isn't a problem if we use `-webkit-text-stroke` instead, but then we [cannot support IE at all](http://caniuse.com/#search=text-stroke).
