### ISSUE TITLE
Underwriters Overflow issue

### ISSUE THREAD

**Issue by BigActual** [Good-Shepherd-Catholic-Radio/Theme-2017#40]
We have so many that we have to come up with an alternative method of showing them. I have two suggestions:
![image](https://user-images.githubusercontent.com/8271108/28505210-a267a602-6fef-11e7-9d9a-7276c999ab31.png)
-or-
![image](https://user-images.githubusercontent.com/8271108/28505237-e29d6a04-6fef-11e7-8dec-a6c15ca866b0.png)

**Comment by BigActual** [comment]
Option 1 is basically a carousel, but maybe it's the right solution. Option 2 isn't bad either though.

**Comment by d4mation** [comment]
Ah, this is what you meant by "overflow". I figured you meant something like they were spilling off the side of the screen.

Randomizing a query using PHP is frowned upon as it prevents the Page from being cached properly and randomized queries are slow. They're disabled by default in WP Engine. Even once this site is moved off our Multisite and to their own install, the Schedule Items and Radio Shows alone are over 1.5k Database Entries in `wp_posts`, so I'd say this qualifies as a larger database.

> Normally we disable ORDER BY RAND() orderings in MySQL queries because this is a big no-no for large databases which we've seen cause massive slow-downs for dozens of our customers. However, you can enable it if you know what you're doing, for example if you cache the results for 5-15 minutes so that you're not pummeling the database with these slow queries.

There are ways around this, however. They just aren't perfect. What we can do instead is Query _all_ of the Underwriters and On-Air Personalities using JavaScript/AJAX and then randomize them that way within the Browser rather than on the Server. In the case of the second Mock, they could then be sliced down to only show 8 as well. This makes the Query the same for PHP each time allowing it to cache the results. Although, this does mean that the On-Air Personalities and Underwriters will load slightly after the rest of the page and push things down as they pop in. 

In the case of the second Mock, is that a button to link to a separate page or is it a button to expand download to show them all? If it is a button to a new page, it will go to the http://gscr.realbigwebsites.com/underwriters/ page where they are currently output with the most recently entered Underwriters first. If those should be randomized as well, we run into the same problems as above.

**Comment by BigActual** [comment]
What about randomize weekly and cache that?
We would have to decide on whether to expand southward with additional items or go to a new page. I'd prefer it to expand in place I suppose.

**Comment by d4mation** [comment]
We could enable `RAND` and then save the results of the Query to a [Transient](https://css-tricks.com/the-deal-with-wordpress-transients/) in the database with an expiry of 1 week. That way on every other time while the cache is valid we only need to do 1 database query. However, I'm thinking that would be a better thing to do once they're on their own install rather than being on our Multisite. Random queries really aren't very efficient.

**Comment by BigActual** [comment]
OK

**Comment by d4mation** [comment]
This issue and #41 I've left open as pretty much all the solutions we discussed above appear to only make sense to implement once their site has been migrated to a separate server.

**Comment by BigActual** [comment]
Client approves the RAND solution with an adjustment. ALL sponsors must receive equal time as starters on the home page, and for that matter in the pole position (First slot). Not random groups where the same 8 are displayed in groups and it' always the same guy in spot one and the same guy in spot 8. It has to be completely impartial and with the same amount of exposure throughout a week. So the query would have to be daily, not weekly.
As you mentioned in #25 we have to address the form in the layout.

**Comment by d4mation** [comment]
Well, there's no way to ensure _EQUAL_ time if it is truly random. They will have equal opportunity to be "starters", but with a random query there is the (small) potential for things to hardly change from day-to-day. The more Underwriters there are, the less chance of there being duplicates within the "starters" on the home page.

**Comment by BigActual** [comment]
To clarify, and document, I believe we identified that the solution would be to make this a rotation instead of a random generation.

**Comment by d4mation** [comment]
Yep, but with this, I still think it is best for it to wait until the site is moved over to their server.

**Comment by d4mation** [comment]
@BigActual 

I can get these set on a Rotation. However, that leads to some potential oddities (Which would probably effect Underwriters more often than On-Air Personalities):

1. When a new Listing is _added_, with the way the query is handled now, it will go to the Top/Front of the list. This is because it is sorting them Most Recent -> Least Recent
    - If a new Underwriter/On-Air Personality were to be added, they would be at the start. However, if the Rotation has already begun, then they would obviously not be at the very Front. They may even loop around to the end depending on the number of results.
2. If a Listing is _deleted_, this is where things get tricky. While it won't effect who is in the "Pole Position" necessarily, it will shift everything forward more quickly. If the idea is to move through the Listings at a rate of 1 per day, then this won't really be an issue. However, I wanted to bring it up.

So, to clarify, is this the functionality we're looking for? This example assumes exactly 9 listings exist, to help show different possibilities. 

Day 1:
A, B, C, D, 
E, F, G, H

Day 2: 
B, C, D, E, 
F, G, H, I

Day 3:
C, D, E, F, 
G, H, I, A

Day 4 (Listing D has been deleted, shifting everything forward by one day):
E, F, G, H, 
I, A, B, C

Day 5 (Listing J has been created. It goes to the end of the Query, and then things loop back around after it)
F, G, H, I
J, A, B, C

**Comment by BigActual** [comment]
One a day is fine. OK on the rest. If it becomes an issue we can deal with it then (punt)

**Comment by d4mation** [comment]
Should the Underwriters/On-Air Personalities offset increment on a _PHP Cron_, or a “Real” Cron?

PHP Cron will increment every day **provided someone visits the website**. A Real Cron though we’ll need to set up some 3rd party web service to hit a URL on our site to tell it to update the offset counter. With a Real Cron technically someone is visiting the site, but it would be automated and fire off on a proper schedule as a Cron should.

I only mention this because let’s say no one visits the site in 3 days, but if someone is keeping track of who should be in the First Slot on a given day and goes and checks and it doesn’t match up with their calendar they'll wonder what’s up.

**Comment by BigActual** [comment]
Real Cron.

**Comment by d4mation** [comment]
Just set this up in Ghost Inspector. It runs daily and hits a URL on our site that tells it to increment both the Offset Counter for Underwriters and On-Air Personalities. 

It checks against a Secret Key stored in the Website's Database to ensure no one discovers the URL and continually increments the counter.

The setting for the Secret Key can be found in the Customizer:
![image](https://user-images.githubusercontent.com/7770631/30331571-36271fc0-97a6-11e7-9f5e-85180bf76cd3.png)

Here's the results of the first run of the Cron. I'm going to make sure whether it says it "failed" if the Key is a mismatch--I don't think Ghost Inspector is configured to care about that whether you tell it to or not. But if the Key is a mismatch, it won't increment anything and that's the important bit.
![image](https://user-images.githubusercontent.com/7770631/30331438-d1fc679e-97a5-11e7-825a-7ef1742fce1a.png)

**Comment by d4mation** [comment]
It indeed did _not_ care if it did not complete successfully, but I added a check to it so it will fail if the incrementation does not complete successfully due to a key mismatch.

This means that if for some reason, the Key changes but Ghost Inspector isn't provided a new key, when the Cron Job fails the next day, the webmaster email will be notified.

They will _not_ be notified if someone finds the URL and is just guessing at it. This only happens if Ghost Inspector is somehow incorrect.
