### ISSUE TITLE
Change Round Play Button to a Rectangle with rounded corners 

### ISSUE THREAD

**Issue by BigActual** [Good-Shepherd-Catholic-Radio/Theme-2017#52]
Match the shape of other buttons on the site. The width of the button should be appropriate to the element. It does not need to be wide, like the [Donate Now] or [On iTunes] buttons.

**Comment by d4mation** [comment]
This isn't technically a button in the same sense as those are, but rather an icon. http://fontawesome.io/icon/play-circle/

I should be able to convert it to a button, but getting the hover styling to work properly as a normal button (The way it becomes hollow/ghost on hover) will take a bit of extra work.

**Comment by d4mation** [comment]
It will take a lot of adjustment with positioning and sizing and such, but I mocked it up quickly in the browser inspector.

![image](https://user-images.githubusercontent.com/7770631/29788337-34f0bd3e-8c00-11e7-8788-81b80bbe338d.png)

I think the rounded button here works better, actually. It doesn't necessarily match other buttons in the Theme, but that also helps it stand out.

**Comment by d4mation** [comment]
Oh, also, the downside to using a square/rectangle button like this:

I cannot make that interior "play" shape transparent. I had to color it white above. Is is because instead of being the color itself, it is now on top of a shape.

While maybe not horribly important, that means that below in the "Now Playing" section, the background will not show through it. That may not matter and it may be undesirable that it does that now anyhow. But that will be lost.

![image](https://user-images.githubusercontent.com/7770631/29788438-90299c7a-8c00-11e7-92b9-89657f2767af.png)

**Comment by d4mation** [comment]
It does look nice when it shows through on Hover though

![image](https://user-images.githubusercontent.com/7770631/29788458-a9f85074-8c00-11e7-96c0-b608bfd1ea3f.png)

**Comment by d4mation** [comment]
However, having transparency for the Button on-Hover with the rounded square/Rectangle will not be an issue. It is only an issue for the default state.

So, I guess it comes down to preference with this. I personally like the circle for it, but I can understand an argument for having everything uniform.

**Comment by BigActual** [comment]
Well, how about switching the other way and making all buttons rounded with the same hover effect as the play button.

**Comment by d4mation** [comment]
Just implemented that on (most) buttons. There's a couple stragglers still.

I had to assign them a white fill however, as otherwise it was a crapshoot as to whether the text would remain readable when placed over images.

Without white background:
![image](https://user-images.githubusercontent.com/7770631/29789436-0fa3db5c-8c04-11e7-97b6-81640b83c281.png)

With white background:
![image](https://user-images.githubusercontent.com/7770631/29789477-32b0517a-8c04-11e7-9d55-62c727373ba9.png)

The white background variant is up now if you want to see it alongside the Play Button.

**Comment by BigActual** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/7681590-283868566_2-s4-v1.png?transparent=1&palette=1&width=50)

**Comment by BigActual** [comment]
In the containers for Support GSCR and Listening Options, would you please drop those buttons down so they sit just up off the bottom of the containers. Look to the boxes to the left and adjust the buttons up and down until they sit nicely in line with the copy in the overlays.
