### ISSUE TITLE
Modify images in the Calendar on the page /radio-show-schedule/

### ISSUE THREAD

**Issue by BigActual** [Good-Shepherd-Catholic-Radio/Theme-2017#63]
Use the perspective of the Now Playing image on the home page to narrow these items for all listings on the calendar.
![image](https://user-images.githubusercontent.com/8271108/29828426-a9277a4e-8caa-11e7-8ba3-912674daadc6.png)

**Comment by d4mation** [comment]
I had to make the images significantly larger in order to crop them in the same way as the "Now Playing" section of the Home Page, but that's all set now.

Just a note though, these images are not quite cropped that same way for the "Up Next" section. The reason you don't really notice is because of the aspect ratio of the "Up Next" blocks in comparison to the "Now Playing" block. The "Up Next" blocks are able to show much closer to the full image at once while the "Now Playing" block couldn't, which is why we cropped it.

![image](https://user-images.githubusercontent.com/7770631/29831092-0f8cdfe8-8cb2-11e7-9965-771ad9852ad9.png)

![image](https://user-images.githubusercontent.com/7770631/29831120-26658972-8cb2-11e7-97d9-7e7002d07ead.png)
