### ISSUE TITLE
Move page title up on top (Z - Axis) of the featured image

### ISSUE THREAD

**Issue by BigActual** [Good-Shepherd-Catholic-Radio/Theme-2017#66]
![image](https://user-images.githubusercontent.com/8271108/29850814-479cfa52-8cfe-11e7-82f0-be3341d50463.png)

**Comment by BigActual** [comment]
Scheduled Items single template and Blog Archive will be different

**Comment by BigActual** [comment]
Blog Single should be included, however.

**Comment by d4mation** [comment]
Post Title on Pages and Post Single now overlay the Featured Image. On Post Single, the Date also goes up there under the Title.

I set it so that this _only_ happens if there is a Featured Image, so Pages or Posts without one set will not be effected.

We may want to alter the Post Title text color in this case though. Depending on the image it will be hard to read.

![image](https://user-images.githubusercontent.com/7770631/29872649-78e049d8-8d5e-11e7-952b-365811e93626.png)

**Comment by BigActual** [comment]
Can you use the same type of overlay from the hero image to ensure contrast behind the yellow?
