### ISSUE TITLE
Adjust image on the events page down 

### ISSUE THREAD

**Issue by BigActual** [Good-Shepherd-Catholic-Radio/Theme-2017#75]
This is probably a global issue where we need to decide what portion of the image to display.

**Comment by d4mation** [comment]
(Radio Shows and Events use the same template for this, so I'm using a Radio Show as an example)

Right now the background positioning for the Featured Images are centered vertically and horizontally. I'm not sure if we could pick something that will globally look good in every single instance. 

I could technically add some kind of control to individual Schedule Items so that per-Radio Show/Event you could choose how the background image should be positioned. But that is pretty heavy-handed. 

Can you give an example where one looks particularly bad? This one doesn't look too bad really, and it is with what I think is one of the "original" images.

![image](https://user-images.githubusercontent.com/7770631/30222837-48c22ab6-9496-11e7-8beb-81e59b469ce0.png)

![image](https://user-images.githubusercontent.com/7770631/30222939-bca11dac-9496-11e7-8d5d-e68f9e47bba6.png)

**Comment by BigActual** [comment]
In understanding how the code works I can learn how to format the images going in. Perhaps some adjustments will need to be done to the code, but until I am able to get a handle on that, I'll attempt to reformat the pics.

**Comment by BigActual** [comment]
Also, this had more to do with all of the other CPTs. Especially the events. The pic I chose shows the right portion of the helpers on the home page, in the events section, but when you go to the Events page, it shows their bellies.
This section is the only one that has the same image on the home page that's used in the archive page for perhaps we could simply separate that and the problem goes away. Place a field in the dashboard for the home page AND separately, create another place to upload the image used on the events page.

What are your thoughts on this suggestion?

**Comment by d4mation** [comment]
Oh, so you're referring to just the Calendar Archive?

I can adjust that one however it is necessary. Since that is a specific instance it isn't a big deal if we have to tweak for that one. I thought you were saying the Hero/Banner image on individual Single CPTs. So, an individual Event or Page.

**Comment by BigActual** [comment]
OK
