### ISSUE TITLE
Google Analytics via Google Tag Manager

### ISSUE THREAD

**Issue by BigActual** [Good-Shepherd-Catholic-Radio/Theme-2017#92]
Copy the code below and paste it onto every page of your website.

- [x] Paste this code as high in the <head> of the page as possible:

```
<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-KX6JZK3');</script>
<!-- End Google Tag Manager -->
```

- [x] Additionally, paste this code immediately after the opening <body> tag:

```
<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-KX6JZK3"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->
```

For more information about installing the Google Tag Manager snippet, visit our Quick Start Guide .

**Comment by d4mation** [comment]
The AJAX Refresh code should properly handle Google Analytics, but if Google Tag Manager is being used to include specific "tags" per-page it may not work correctly without some modification. Just giving you a heads up with that since from my end, GTM is a black box of sorts since I include this code and it lets you include whatever code you like. 

(I removed this from the v1.1 Milestone since I know you want this ASAP. Everything in v1.1 is stuff that will take much longer and will take some planning/co-operation from the client to get done)
